### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by MuellerNicolas** [Jopyth/MMM-Buttons#12]
I am running magic mirror in a docker container however, after fixing an error with electron by installing electron by hand and editing the path in the package.json see issue: https://github.com/Jopyth/MMM-Buttons/issues/7

Now magic mirror can't start and i get the following docker logs:
```
[2020-12-16 18:34:53.575] [ERROR]  Error: The module '/opt/magic_mirror/modules/MMM-Buttons/node_modules/epoll/build/Release/epoll.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/magic_mirror/modules/MMM-Buttons/node_modules/bindings/bindings.js:112:48)
    at /opt/magic_mirror/modules/MMM-Buttons/node_modules/epoll/epoll.js:7:31
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Buttons/node_modules/epoll/epoll.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```
i have already tried `npm rebuild`  and `./node_modules/.bin/electron-rebuild`
Does this has to do with the electron version? What can i possibly do to fix the issue?

Thank you for your support :)

excuse me, @Jopyth what electron version are you using? (It isn't specified in the package.json file)

**Comment by gonzonia** [comment]
I'm having the same issue.

**Comment by gonzonia** [comment]
So, I think I got it working (or at least loading, haven't tested my buttons yet). I removed the MMM-Buttons directory. Reinstalled. When I did the initial install I ran 'sudo npm install' and got the errror. Running 'npm install' after seemed to fix it.

**Comment by MuellerNicolas** [comment]
> So, I think I got it working (or at least loading, haven't tested my buttons yet). I removed the MMM-Buttons directory. Reinstalled. When I did the initial install I ran 'sudo npm install' and got the errror. Running 'npm install' after seemed to fix it. 
>  

Are you also using a docker container for magic mirror?

**Comment by gonzonia** [comment]
No. I'm running on a pi 4
