### ISSUE TITLE
npm rebuild fix

### ISSUE THREAD

**Issue by fratzinger** [Jopyth/MMM-Buttons#2]
I got an error after installing the module. 
```
Whoops! There was an uncaught exception...
Error: Module version mismatch. Expected 48, got 53.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/MMM-Buttons/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Buttons/node_modules/epoll/epoll.js:1:99)
    at Module._compile (module.js:570:32)
```
So I googled a bit and found a solution:
```
npm rebuild
```
After I ran this in the MMM-Buttons-folder it works. I don't know exactly what it did, but I want to inform the contributors or other folks who want to install this.

**Comment by linuxs** [comment]
Worked for me also.

**Comment by sdetweil** [comment]
see pr #18
